/**
 * 일회용 이메일 도메인 차단 목록
 * 주요 100개+ 일회용 이메일 서비스
 */

const DISPOSABLE_DOMAINS = new Set([
  // 가장 많이 사용되는 일회용 이메일
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
  "guerrillamailblock.com", "grr.la", "sharklasers.com",
  "mailinator.com", "mailinator2.com", "maildrop.cc",
  "tempmail.com", "temp-mail.org", "temp-mail.io",
  "throwaway.email", "throwaway.com",
  "yopmail.com", "yopmail.fr", "yopmail.net",
  "10minutemail.com", "10minutemail.net", "10minute.email",
  "minutemail.com",
  "dispostable.com", "disposableemailaddresses.com",
  "trashmail.com", "trashmail.net", "trashmail.me", "trashmail.org",
  "mailnesia.com", "mailnull.com",
  "getnada.com", "nada.email",
  "emailondeck.com",
  "fakeinbox.com", "fakemail.net",
  "tempinbox.com",
  "discard.email",
  "mailcatch.com",
  "mytemp.email",
  "mohmal.com",
  "burnermail.io",
  "harakirimail.com",
  "jetable.org",
  "crazymailing.com",
  "filzmail.com",
  "inboxbear.com",
  "mailexpire.com",
  "mailforspam.com",
  "safetymail.info",
  "spamgourmet.com",
  "tempr.email", "tempemail.net",
  "tempail.com",
  "emailfake.com",
  "generator.email",
  "guerrillamail.de",
  "maildrop.com",
  "mailtemp.net",
  "nowmymail.com",
  "privy-mail.com",
  "sharklasers.com",
  "spam4.me",
  "spamfree24.org",
  "trashymail.com",
  "wegwerfemail.de",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "einrot.com",
  "nomail.xl.cx",
  "rcpt.at",
  "reallymymail.com",
  "rmqkr.net",
  "mailbox92.biz",
  "tmails.net",
  "tmpmail.net", "tmpmail.org",
  "binkmail.com",
  "bobmail.info",
  "chammy.info",
  "devnullmail.com",
  "fastacura.com",
  "filzmail.com",
  "getairmail.com",
  "gishpuppy.com",
  "grandmamail.com",
  "haltospam.com",
  "hulapla.de",
  "incognitomail.org",
  "klzlk.com",
  "lackmail.net",
  "lortemail.dk",
  "mailblocks.com",
  "mailmoat.com",
  "mailshell.com",
  "mailzilla.com",
  "nomail.xl.cx",
  "nospam.ze.tc",
  "objectmail.com",
  "obobbo.com",
  "onewaymail.com",
  "owlpic.com",
  "proxymail.eu",
  "punkass.com",
  "shieldedmail.com",
  "slaskpost.se",
  "spambox.us",
  "spamcero.com",
  "spamday.com",
  "spamex.com",
  "tempinbox.co.uk",
  "thankyou2010.com",
  "veryrealemail.com",
  "wasteland.rfc822.org",
  "webemail.me",
  "zetmail.com",
]);

/**
 * 이메일이 일회용인지 확인
 * @returns true면 일회용 (차단해야 함)
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}
